trigger:
  branches:
    include:
      - dev
      - staging
      - main
      - development  # optional, if that's your actual branch

pool:
  name: SandBoxAgent

stages:
# ==========================================================
# 1️⃣ DEV STAGE
# ==========================================================
- stage: Dev
  displayName: "Deploy to Dev"
  variables:
    - group: DevSettings
  jobs:
    - deployment: DeployToDev
      displayName: "Deploy to Development Environment"
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  echo "---------------------------------"
                  echo "Branch: $(Build.SourceBranch)"
                  echo "Deploying to DEV environment..."
                  echo "Environment: $(envName)"
                  echo "Database Server: $(dbServer)"
                  echo "---------------------------------"
                displayName: "Echo Dev Variables"

# ==========================================================
# 2️⃣ STAGING STAGE
# ==========================================================
- stage: Staging
  displayName: "Deploy to Staging"
  dependsOn: Dev
  condition: succeeded()
  variables:
    - group: StagingSettings
  jobs:
    - deployment: DeployToStaging
      displayName: "Deploy to Staging Environment"
      environment: staging
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  echo "---------------------------------"
                  echo "Deploying to STAGING environment..."
                  echo "Environment: $(envName)"
                  echo "Database Server: $(dbServer)"
                  echo "---------------------------------"
                displayName: "Echo Staging Variables"

# ==========================================================
# 3️⃣ PRODUCTION STAGE
# ==========================================================
- stage: Prod
  displayName: "Deploy to Production"
  dependsOn: Staging
  condition: succeeded()
  variables:
    - group: ProdSettings
  jobs:
    - deployment: DeployToProd
      displayName: "Deploy to Production Environment"
      environment: production
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  echo "---------------------------------"
                  echo "Deploying to PRODUCTION environment..."
                  echo "Environment: $(envName)"
                  echo "Database Server: $(dbServer)"
                  echo "---------------------------------"
                displayName: "Echo Prod Variables"
