trigger:
  branches:
    include:
      - dev
      - staging
      - main

pool:
    name: SandBoxAgent

stages:
- stage: Dev
  displayName: "Deploy to Dev"
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
  jobs:
    - deployment: DeployToDev
      displayName: "Deploy to Development Environment"
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo "Deploying to Dev environment..."
                displayName: "Deployment step"

- stage: Staging
  displayName: "Deploy to Staging"
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/staging')
  jobs:
    - deployment: DeployToStaging
      displayName: "Deploy to Staging Environment"
      environment: staging
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo "Deploying to Staging environment..."
                displayName: "Deployment step"

- stage: Prod
  displayName: "Deploy to Production"
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
    - deployment: DeployToProd
      displayName: "Deploy to Production Environment"
      environment: production
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo "Deploying to Production environment..."
                displayName: "Deployment step"
